enum UserRole {
  child,
  parent,
  teacher,
}

class UserProfile {
  final String id;
  final UserRole role;
  final String? email; // Optional for child
  final String pseudo; // Username, useful for child
  final String? fullName; // Optional for adults
  final String? affiliationCode; // The code generated by a child
  final int sortOrder;

  UserProfile({
    required this.id,
    required this.role,
    this.email,
    required this.pseudo,
    this.fullName,
    this.affiliationCode,
    this.sortOrder = 0,
  });

  UserProfile copyWith({
    String? id,
    UserRole? role,
    String? email,
    String? pseudo,
    String? fullName,
    String? affiliationCode,
    int? sortOrder,
  }) {
    return UserProfile(
      id: id ?? this.id,
      role: role ?? this.role,
      email: email ?? this.email,
      pseudo: pseudo ?? this.pseudo,
      fullName: fullName ?? this.fullName,
      affiliationCode: affiliationCode ?? this.affiliationCode,
      sortOrder: sortOrder ?? this.sortOrder,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is UserProfile &&
        other.id == id &&
        other.role == role &&
        other.email == email &&
        other.pseudo == pseudo &&
        other.fullName == fullName &&
        other.affiliationCode == affiliationCode &&
        other.sortOrder == sortOrder;
  }

  @override
  int get hashCode {
    return id.hashCode ^
        role.hashCode ^
        email.hashCode ^
        pseudo.hashCode ^
        fullName.hashCode ^
        affiliationCode.hashCode ^
        sortOrder.hashCode;
  }
}
