-- ==========================================================
-- 15_CREATE_STATEMENTS_TABLE.SQL
-- Crée la table des statements (logs de réponses des enfants)
-- active la RLS et définit les politiques de sécurité.
-- ==========================================================

CREATE TABLE IF NOT EXISTS public.statements (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    child_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    operand1 INTEGER NOT NULL,
    operand2 INTEGER NOT NULL,
    success BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Activation du RLS
ALTER TABLE public.statements ENABLE ROW LEVEL SECURITY;

-- Politiques de sécurité
DROP POLICY IF EXISTS "Insert_own_statements" ON public.statements;
CREATE POLICY "Insert_own_statements" ON public.statements 
    FOR INSERT 
    WITH CHECK (auth.uid() = child_id);

DROP POLICY IF EXISTS "Select_statements" ON public.statements;
CREATE POLICY "Select_statements" ON public.statements 
    FOR SELECT 
    USING (
        -- L'enfant peut voir ses propres statements
        auth.uid() = child_id OR
        -- Les adultes affiliés à cet enfant peuvent voir ses statements
        EXISTS (
            SELECT 1 FROM public.affiliations a
            WHERE a.child_id = statements.child_id AND a.adult_id = auth.uid()
        ) OR
        -- Les enseignants qui ont l'élève dans une de leurs classes peuvent voir ses statements
        EXISTS (
            SELECT 1 FROM public.classes c
            JOIN public.class_students cs ON c.id = cs.class_id
            WHERE cs.student_id = statements.child_id AND c.teacher_id = auth.uid()
        )
    );
